### ISSUE TITLE
Problem in video sound.

### ISSUE THREAD

**Issue by gauravthummar** [mooncatventures-group/RTSPPlay#5]
When i am run this url rtsp://media-us-2.soundreach.net/slcn_lifestyle.sdp i have problem for sound. the second one url rtsp://172.18.143.79:558/live.sdp i also have big problem of disturbance sound. there are some extra noise i get. so please suggest me how can i resolve this problem of extra noise.

**Comment by mooncatventures-group** [comment]
There is some slight distorting when testing with avdemoplay2 also, there seems to be less when using tcp rather than udp. The stream played in both confiigurations.

For Rtspplay add ?tcp to the end of the url to force TCP.

The input sound source you are using does not appear very "clean", what format is this.

**Comment by gauravthummar** [comment]
where should i need to add TCP. i am not getting. i am get voice disturbance in both of url. but i am not getting disturbance in one of other application. this one http://www.chupamobile.com/products/details/942/VideoStream+SDK+for+iOS/

**Comment by mooncatventures-group** [comment]
after the url add this ?tcp

So let me get this straight you are comparing a free application thats hasn't been updated in a while with a new commercial api.
We haven't completely evaluated videoStream sdk yet, from some of the reviews it appears to work good for some people and not so good for some others.

It seems to be equivalent to our streammoreplay but we have a few features they don't and they have a few that we don't such as mms. 
Pricing wise, since we have no set price and we tailor solutions to need I suspect we may do better.

I tried this link with AvDemoPlay2 commercial  version (The demo here requires using your own  audio library ie. audioQueues, audioUnits, openAL or even something commercial like radioTunes) , the commercial version has our advancedAudio Library.

Please join our Facebook developers group to learn more about any of our platforms or contact us about getting an evaluation demo.

**Comment by mooncatventures-group** [comment]
cannot duplicate, testing with similar input shows no issues.
